/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface WyvernStaticAbiInterface extends utils.Interface {
  contractName: "WyvernStaticAbi";
  functions: {
    "and(bytes,address[7],uint8[2],uint256[6],bytes,bytes)": FunctionFragment;
    "any(bytes,address[7],uint8[2],uint256[6],bytes,bytes)": FunctionFragment;
    "anyAddOne(bytes,address[7],uint8[2],uint256[6],bytes,bytes)": FunctionFragment;
    "anyNoFill(bytes,address[7],uint8[2],uint256[6],bytes,bytes)": FunctionFragment;
    "anySingle(bytes,address[7],uint8,uint256[6],bytes)": FunctionFragment;
    "atomicizer()": FunctionFragment;
    "dumbSequenceExact(bytes,address[7],uint8[2],uint256[6],bytes,bytes)": FunctionFragment;
    "name()": FunctionFragment;
    "or(bytes,address[7],uint8[2],uint256[6],bytes,bytes)": FunctionFragment;
    "sequenceAnyAfter(bytes,address[7],uint8,uint256[6],bytes)": FunctionFragment;
    "sequenceExact(bytes,address[7],uint8,uint256[6],bytes)": FunctionFragment;
    "split(bytes,address[7],uint8[2],uint256[6],bytes,bytes)": FunctionFragment;
    "splitAddOne(bytes,address[7],uint8[2],uint256[6],bytes,bytes)": FunctionFragment;
    "swapExact(bytes,address[7],uint8[2],uint256[6],bytes,bytes)": FunctionFragment;
    "swapForever(bytes,address[7],uint8[2],uint256[6],bytes,bytes)": FunctionFragment;
    "swapOneForOneERC1155(bytes,address[7],uint8[2],uint256[6],bytes,bytes)": FunctionFragment;
    "swapOneForOneERC1155Decoding(bytes,address[7],uint8[2],uint256[6],bytes,bytes)": FunctionFragment;
    "swapOneForOneERC721(bytes,address[7],uint8[2],uint256[6],bytes,bytes)": FunctionFragment;
    "swapOneForOneERC721Decoding(bytes,address[7],uint8[2],uint256[6],bytes,bytes)": FunctionFragment;
    "test()": FunctionFragment;
    "transferERC1155Exact(bytes,address[7],uint8,uint256[6],bytes)": FunctionFragment;
    "transferERC20Exact(bytes,address[7],uint8,uint256[6],bytes)": FunctionFragment;
    "transferERC721Exact(bytes,address[7],uint8,uint256[6],bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "and",
    values: [
      BytesLike,
      string[],
      [BigNumberish, BigNumberish],
      BigNumberish[],
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "any",
    values: [
      BytesLike,
      string[],
      [BigNumberish, BigNumberish],
      BigNumberish[],
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "anyAddOne",
    values: [
      BytesLike,
      string[],
      [BigNumberish, BigNumberish],
      BigNumberish[],
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "anyNoFill",
    values: [
      BytesLike,
      string[],
      [BigNumberish, BigNumberish],
      BigNumberish[],
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "anySingle",
    values: [BytesLike, string[], BigNumberish, BigNumberish[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "atomicizer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dumbSequenceExact",
    values: [
      BytesLike,
      string[],
      [BigNumberish, BigNumberish],
      BigNumberish[],
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "or",
    values: [
      BytesLike,
      string[],
      [BigNumberish, BigNumberish],
      BigNumberish[],
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "sequenceAnyAfter",
    values: [BytesLike, string[], BigNumberish, BigNumberish[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sequenceExact",
    values: [BytesLike, string[], BigNumberish, BigNumberish[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "split",
    values: [
      BytesLike,
      string[],
      [BigNumberish, BigNumberish],
      BigNumberish[],
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "splitAddOne",
    values: [
      BytesLike,
      string[],
      [BigNumberish, BigNumberish],
      BigNumberish[],
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapExact",
    values: [
      BytesLike,
      string[],
      [BigNumberish, BigNumberish],
      BigNumberish[],
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapForever",
    values: [
      BytesLike,
      string[],
      [BigNumberish, BigNumberish],
      BigNumberish[],
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapOneForOneERC1155",
    values: [
      BytesLike,
      string[],
      [BigNumberish, BigNumberish],
      BigNumberish[],
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapOneForOneERC1155Decoding",
    values: [
      BytesLike,
      string[],
      [BigNumberish, BigNumberish],
      BigNumberish[],
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapOneForOneERC721",
    values: [
      BytesLike,
      string[],
      [BigNumberish, BigNumberish],
      BigNumberish[],
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapOneForOneERC721Decoding",
    values: [
      BytesLike,
      string[],
      [BigNumberish, BigNumberish],
      BigNumberish[],
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "test", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferERC1155Exact",
    values: [BytesLike, string[], BigNumberish, BigNumberish[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferERC20Exact",
    values: [BytesLike, string[], BigNumberish, BigNumberish[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferERC721Exact",
    values: [BytesLike, string[], BigNumberish, BigNumberish[], BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "and", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "any", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "anyAddOne", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "anyNoFill", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "anySingle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "atomicizer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "dumbSequenceExact",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "or", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sequenceAnyAfter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sequenceExact",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "split", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "splitAddOne",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swapExact", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapForever",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapOneForOneERC1155",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapOneForOneERC1155Decoding",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapOneForOneERC721",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapOneForOneERC721Decoding",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "test", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferERC1155Exact",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferERC20Exact",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferERC721Exact",
    data: BytesLike
  ): Result;

  events: {};
}

export interface WyvernStaticAbi extends BaseContract {
  contractName: "WyvernStaticAbi";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: WyvernStaticAbiInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    and(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;

    any(
      arg0: BytesLike,
      arg1: string[],
      arg2: [BigNumberish, BigNumberish],
      arg3: BigNumberish[],
      arg4: BytesLike,
      arg5: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    anyAddOne(
      arg0: BytesLike,
      arg1: string[],
      arg2: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      arg4: BytesLike,
      arg5: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    anyNoFill(
      arg0: BytesLike,
      arg1: string[],
      arg2: [BigNumberish, BigNumberish],
      arg3: BigNumberish[],
      arg4: BytesLike,
      arg5: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    anySingle(
      arg0: BytesLike,
      arg1: string[],
      arg2: BigNumberish,
      arg3: BigNumberish[],
      arg4: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;

    atomicizer(overrides?: CallOverrides): Promise<[string]>;

    dumbSequenceExact(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      cdata: BytesLike,
      arg5: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    name(overrides?: CallOverrides): Promise<[string]>;

    or(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;

    sequenceAnyAfter(
      extra: BytesLike,
      addresses: string[],
      howToCall: BigNumberish,
      uints: BigNumberish[],
      cdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;

    sequenceExact(
      extra: BytesLike,
      addresses: string[],
      howToCall: BigNumberish,
      uints: BigNumberish[],
      cdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;

    split(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    splitAddOne(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    swapExact(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    swapForever(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    swapOneForOneERC1155(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    swapOneForOneERC1155Decoding(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    swapOneForOneERC721(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    swapOneForOneERC721Decoding(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    test(overrides?: CallOverrides): Promise<[void]>;

    transferERC1155Exact(
      extra: BytesLike,
      addresses: string[],
      howToCall: BigNumberish,
      arg3: BigNumberish[],
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;

    transferERC20Exact(
      extra: BytesLike,
      addresses: string[],
      howToCall: BigNumberish,
      arg3: BigNumberish[],
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;

    transferERC721Exact(
      extra: BytesLike,
      addresses: string[],
      howToCall: BigNumberish,
      arg3: BigNumberish[],
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;
  };

  and(
    extra: BytesLike,
    addresses: string[],
    howToCalls: [BigNumberish, BigNumberish],
    uints: BigNumberish[],
    data: BytesLike,
    counterdata: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  any(
    arg0: BytesLike,
    arg1: string[],
    arg2: [BigNumberish, BigNumberish],
    arg3: BigNumberish[],
    arg4: BytesLike,
    arg5: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  anyAddOne(
    arg0: BytesLike,
    arg1: string[],
    arg2: [BigNumberish, BigNumberish],
    uints: BigNumberish[],
    arg4: BytesLike,
    arg5: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  anyNoFill(
    arg0: BytesLike,
    arg1: string[],
    arg2: [BigNumberish, BigNumberish],
    arg3: BigNumberish[],
    arg4: BytesLike,
    arg5: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  anySingle(
    arg0: BytesLike,
    arg1: string[],
    arg2: BigNumberish,
    arg3: BigNumberish[],
    arg4: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  atomicizer(overrides?: CallOverrides): Promise<string>;

  dumbSequenceExact(
    extra: BytesLike,
    addresses: string[],
    howToCalls: [BigNumberish, BigNumberish],
    uints: BigNumberish[],
    cdata: BytesLike,
    arg5: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  name(overrides?: CallOverrides): Promise<string>;

  or(
    extra: BytesLike,
    addresses: string[],
    howToCalls: [BigNumberish, BigNumberish],
    uints: BigNumberish[],
    data: BytesLike,
    counterdata: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  sequenceAnyAfter(
    extra: BytesLike,
    addresses: string[],
    howToCall: BigNumberish,
    uints: BigNumberish[],
    cdata: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  sequenceExact(
    extra: BytesLike,
    addresses: string[],
    howToCall: BigNumberish,
    uints: BigNumberish[],
    cdata: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  split(
    extra: BytesLike,
    addresses: string[],
    howToCalls: [BigNumberish, BigNumberish],
    uints: BigNumberish[],
    data: BytesLike,
    counterdata: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  splitAddOne(
    extra: BytesLike,
    addresses: string[],
    howToCalls: [BigNumberish, BigNumberish],
    uints: BigNumberish[],
    data: BytesLike,
    counterdata: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  swapExact(
    extra: BytesLike,
    addresses: string[],
    howToCalls: [BigNumberish, BigNumberish],
    uints: BigNumberish[],
    data: BytesLike,
    counterdata: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  swapForever(
    extra: BytesLike,
    addresses: string[],
    howToCalls: [BigNumberish, BigNumberish],
    uints: BigNumberish[],
    data: BytesLike,
    counterdata: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  swapOneForOneERC1155(
    extra: BytesLike,
    addresses: string[],
    howToCalls: [BigNumberish, BigNumberish],
    uints: BigNumberish[],
    data: BytesLike,
    counterdata: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  swapOneForOneERC1155Decoding(
    extra: BytesLike,
    addresses: string[],
    howToCalls: [BigNumberish, BigNumberish],
    uints: BigNumberish[],
    data: BytesLike,
    counterdata: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  swapOneForOneERC721(
    extra: BytesLike,
    addresses: string[],
    howToCalls: [BigNumberish, BigNumberish],
    uints: BigNumberish[],
    data: BytesLike,
    counterdata: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  swapOneForOneERC721Decoding(
    extra: BytesLike,
    addresses: string[],
    howToCalls: [BigNumberish, BigNumberish],
    uints: BigNumberish[],
    data: BytesLike,
    counterdata: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  test(overrides?: CallOverrides): Promise<void>;

  transferERC1155Exact(
    extra: BytesLike,
    addresses: string[],
    howToCall: BigNumberish,
    arg3: BigNumberish[],
    data: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  transferERC20Exact(
    extra: BytesLike,
    addresses: string[],
    howToCall: BigNumberish,
    arg3: BigNumberish[],
    data: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  transferERC721Exact(
    extra: BytesLike,
    addresses: string[],
    howToCall: BigNumberish,
    arg3: BigNumberish[],
    data: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  callStatic: {
    and(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    any(
      arg0: BytesLike,
      arg1: string[],
      arg2: [BigNumberish, BigNumberish],
      arg3: BigNumberish[],
      arg4: BytesLike,
      arg5: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    anyAddOne(
      arg0: BytesLike,
      arg1: string[],
      arg2: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      arg4: BytesLike,
      arg5: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    anyNoFill(
      arg0: BytesLike,
      arg1: string[],
      arg2: [BigNumberish, BigNumberish],
      arg3: BigNumberish[],
      arg4: BytesLike,
      arg5: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    anySingle(
      arg0: BytesLike,
      arg1: string[],
      arg2: BigNumberish,
      arg3: BigNumberish[],
      arg4: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    atomicizer(overrides?: CallOverrides): Promise<string>;

    dumbSequenceExact(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      cdata: BytesLike,
      arg5: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<string>;

    or(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    sequenceAnyAfter(
      extra: BytesLike,
      addresses: string[],
      howToCall: BigNumberish,
      uints: BigNumberish[],
      cdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    sequenceExact(
      extra: BytesLike,
      addresses: string[],
      howToCall: BigNumberish,
      uints: BigNumberish[],
      cdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    split(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    splitAddOne(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapExact(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapForever(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapOneForOneERC1155(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapOneForOneERC1155Decoding(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapOneForOneERC721(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapOneForOneERC721Decoding(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    test(overrides?: CallOverrides): Promise<void>;

    transferERC1155Exact(
      extra: BytesLike,
      addresses: string[],
      howToCall: BigNumberish,
      arg3: BigNumberish[],
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    transferERC20Exact(
      extra: BytesLike,
      addresses: string[],
      howToCall: BigNumberish,
      arg3: BigNumberish[],
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    transferERC721Exact(
      extra: BytesLike,
      addresses: string[],
      howToCall: BigNumberish,
      arg3: BigNumberish[],
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    and(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    any(
      arg0: BytesLike,
      arg1: string[],
      arg2: [BigNumberish, BigNumberish],
      arg3: BigNumberish[],
      arg4: BytesLike,
      arg5: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    anyAddOne(
      arg0: BytesLike,
      arg1: string[],
      arg2: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      arg4: BytesLike,
      arg5: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    anyNoFill(
      arg0: BytesLike,
      arg1: string[],
      arg2: [BigNumberish, BigNumberish],
      arg3: BigNumberish[],
      arg4: BytesLike,
      arg5: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    anySingle(
      arg0: BytesLike,
      arg1: string[],
      arg2: BigNumberish,
      arg3: BigNumberish[],
      arg4: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    atomicizer(overrides?: CallOverrides): Promise<BigNumber>;

    dumbSequenceExact(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      cdata: BytesLike,
      arg5: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    or(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sequenceAnyAfter(
      extra: BytesLike,
      addresses: string[],
      howToCall: BigNumberish,
      uints: BigNumberish[],
      cdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sequenceExact(
      extra: BytesLike,
      addresses: string[],
      howToCall: BigNumberish,
      uints: BigNumberish[],
      cdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    split(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    splitAddOne(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapExact(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapForever(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapOneForOneERC1155(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapOneForOneERC1155Decoding(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapOneForOneERC721(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapOneForOneERC721Decoding(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    test(overrides?: CallOverrides): Promise<BigNumber>;

    transferERC1155Exact(
      extra: BytesLike,
      addresses: string[],
      howToCall: BigNumberish,
      arg3: BigNumberish[],
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferERC20Exact(
      extra: BytesLike,
      addresses: string[],
      howToCall: BigNumberish,
      arg3: BigNumberish[],
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferERC721Exact(
      extra: BytesLike,
      addresses: string[],
      howToCall: BigNumberish,
      arg3: BigNumberish[],
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    and(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    any(
      arg0: BytesLike,
      arg1: string[],
      arg2: [BigNumberish, BigNumberish],
      arg3: BigNumberish[],
      arg4: BytesLike,
      arg5: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    anyAddOne(
      arg0: BytesLike,
      arg1: string[],
      arg2: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      arg4: BytesLike,
      arg5: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    anyNoFill(
      arg0: BytesLike,
      arg1: string[],
      arg2: [BigNumberish, BigNumberish],
      arg3: BigNumberish[],
      arg4: BytesLike,
      arg5: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    anySingle(
      arg0: BytesLike,
      arg1: string[],
      arg2: BigNumberish,
      arg3: BigNumberish[],
      arg4: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    atomicizer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    dumbSequenceExact(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      cdata: BytesLike,
      arg5: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    or(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    sequenceAnyAfter(
      extra: BytesLike,
      addresses: string[],
      howToCall: BigNumberish,
      uints: BigNumberish[],
      cdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    sequenceExact(
      extra: BytesLike,
      addresses: string[],
      howToCall: BigNumberish,
      uints: BigNumberish[],
      cdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    split(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    splitAddOne(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    swapExact(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    swapForever(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    swapOneForOneERC1155(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    swapOneForOneERC1155Decoding(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    swapOneForOneERC721(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    swapOneForOneERC721Decoding(
      extra: BytesLike,
      addresses: string[],
      howToCalls: [BigNumberish, BigNumberish],
      uints: BigNumberish[],
      data: BytesLike,
      counterdata: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    test(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferERC1155Exact(
      extra: BytesLike,
      addresses: string[],
      howToCall: BigNumberish,
      arg3: BigNumberish[],
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferERC20Exact(
      extra: BytesLike,
      addresses: string[],
      howToCall: BigNumberish,
      arg3: BigNumberish[],
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferERC721Exact(
      extra: BytesLike,
      addresses: string[],
      howToCall: BigNumberish,
      arg3: BigNumberish[],
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
